# Sample .travis.yml for R projects

language: r
warnings_are_errors: true
sudo: required
cache: packages


r_packages:
  - covr

r_github_packages:
  - MartinRoth/knmiR@includeEOBS

after_success:
  - Rscript -e 'covr::codecov()'
